#!/usr/bin/env python3.3

from cnorm.parsing.declaration import Declaration
from cnorm.passes import to_c
import sys

if len(sys.argv) != 2:
    print("Usage: ./mouli test1 //nom du test\n YOU NEED TO HAVE THE FILE \"marvin.py\" IN THE SAME DIRECTORY")
    exit(1)

try:
    import marvin
except ImportError:
    print("Can't find module marvin, please place your 'marvin.py' here")
    exit(1)

test = sys.argv[1]

fileTest = open(test + ".c", "r")
whatTest = fileTest.read()
fileAnswer = open(test + ".res", "r")
ours = fileAnswer.read()

cparse = Declaration()
ast = cparse.parse(whatTest)
yours = ""
for decl in ast.body:
    yours += marvin.marvin(decl)

y = []
ry = yours.find("\n")
while ry != -1:
    y.append(yours[0:ry])
    yours = yours[ry + 1:]
    ry = yours.find("\n")

t = []
rt = whatTest.find("\n")
while rt != -1:
    t.append(whatTest[0:rt])
    whatTest = whatTest[rt + 1:]
    rt = whatTest.find("\n")

o = []
ro = ours.find("\n")
while ro != -1:
    o.append(ours[0:ro])
    ours = ours[ro + 1:]
    ro = ours.find("\n")

i = 0
note = 0
blue = "\033[34m"
red = "\033[31m"
green = "\033[32m"
yellow = "\033[33m"
end = "\033[00m"
print("Legend: [test]: [yours] | [ours]")
def strcmp(s1, s2):
    iMax = len(s1)
    jMax = len(s2)
    i = j = 0
    while i < iMax and j < jMax:
        if s1[i] != s2[j]:
            return i
        i += 1
        j += 1
    if i < iMax or j < jMax:
        return i
    return -1

for line in y:
    if i >= len(o):
        exit(1)
    diff = strcmp(line, o[i])
    if diff != -1:
        begY = line[:diff]
        endY = line[diff:]
        begO = o[i][:diff]
        endO = o[i][diff:]
        fmt = "[" + yellow + "%s" + end + "]: [%s" + red + "%s" + end + "] | [" +green+ "%s" + end + "%s]"
        print (fmt % (t[i], begY, endY, begO, endO))
    else:
        note += 1
        fmt = "[" + blue + "%s" + end + "]: [%s] | [" +green+ "%s" + end + "]"
        print (fmt % (t[i], line, o[i]))
    i += 1
print("Note: %d/%d" % (note, i))
